{% set name = "toml-f" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/toml-f/toml-f/releases/download/v{{ version }}/toml-f-{{ version }}.tar.xz
  sha256: 6b49013d3bcd1043494c140d7b2da6b0cedd87648e4fc5179fcfcf41226d3232
  patches:
    - no-test-drive.patch

build:
  number: 2
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}  # [unix]
    - {{ stdlib('m2w64_c') }}  # [win]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - meson
    - ninja
    - toml-test

test:
  requires:
    - pkg-config
  commands:
    - pkg-config {{ name }} --exact-version {{ version }}
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
    - test ! -f $PREFIX/lib/lib{{ name }}.a  # [unix]

about:
  home: https://toml-f.readthedocs.io
  dev_url: https://github.com/toml-f/toml-f
  doc_url: https://toml-f.github.io/toml-f
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-Apache
    - LICENSE-MIT
  summary: >-
    TOML parser implementation for data serialization and deserialization in Fortran 

extra:
  recipe-maintainers:
    - awvwgk
