{% set name = "toml-f" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dff1bf3466ff346d2dee24440d1a4728e71051fe34d5c282b6ce7e6dc3ce0de9
  patches:
    - no-test-drive.patch  # [win]
    - meson-wrap.patch  # [unix]

build:
  number: 0
  script:
    - set -ex  # [unix]
    - meson setup _build ${MESON_ARGS:---prefix=${PREFIX} --libdir=lib}  # [unix]
    - meson setup _build --prefix=%PREFIX% --libdir=lib  # [win]
    - meson compile -C _build
    - meson install -C _build --no-rebuild
  run_exports:
    - {{ pin_subpackage('toml-f', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - meson
    - ninja

test:
  requires:
    - pkg-config
  commands:
    - set PKG_CONFIG_PATH=%PREFIX%\lib\pkgconfig  # [win]
    - pkg-config {{ name }} --exact-version {{ version }}
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]

about:
  home: https://github.com/toml-f/toml-f
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-Apache
    - LICENSE-MIT
  summary: >-
    TOML parser implementation for data serialization and deserialization in Fortran 
  doc_url: https://toml-f.github.io/toml-f

extra:
  recipe-maintainers:
    - awvwgk
